#!/usr/bin/env python3
"""Generate the canonical-worker drop-in route for brmste.com/networks.

The live brmste.com edge was mapped with the Cloudflare MCP server: the site is
served by the Worker `brmste-canonical-leader-router` (id 905109fa4cb04c15a0d66c4e66479a66),
which emits its HTML **inline** from worker code — there is no Workers-Sites KV,
no D1, and R2 is not wired for page content. So the faithful way to add
`/networks` to the main ("our main business") worker is a self-contained route
function that returns the page HTML inline, needing NO binding at all.

This script embeds `site/networks/index.html` (the single source of truth) into
`site/networks/canonical-route.js` so the two never drift. Re-run it whenever the
page changes; CI can enforce sync with `--check`.

Usage:
  python3 scripts/build-networks-route.py            # write canonical-route.js
  python3 scripts/build-networks-route.py --check    # exit 1 if it would change

No third-party dependencies; standard library only.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_HTML = REPO_ROOT / "site" / "networks" / "index.html"
OUT_JS = REPO_ROOT / "site" / "networks" / "canonical-route.js"

# Canonical worker facts, verified live via the Cloudflare MCP server.
CANONICAL_WORKER = "brmste-canonical-leader-router"
CANONICAL_WORKER_ID = "905109fa4cb04c15a0d66c4e66479a66"


def escape_for_template_literal(html: str) -> str:
    """Make HTML safe to embed inside a JS backtick template literal."""
    # Order matters: escape backslashes first, then backticks and ${ sequences.
    html = html.replace("\\", "\\\\")
    html = html.replace("`", "\\`")
    html = html.replace("${", "\\${")
    return html


JS_TEMPLATE = r"""/**
 * BRMSTE Networks — drop-in `/networks` route for the canonical brmste.com Worker.
 *
 * AUTO-GENERATED by scripts/build-networks-route.py from site/networks/index.html.
 * Do not edit by hand; edit index.html and re-run the generator (CI checks sync).
 *
 * Why this exists: the live brmste.com site is served by the Cloudflare Worker
 * `__WORKER__` (id __WORKER_ID__), mapped via the Cloudflare MCP server. That
 * worker emits HTML *inline* from code — there is no Workers-Sites KV, no D1, and
 * R2 is not wired for page content. So the faithful way to add `/networks` to the
 * main worker is this self-contained function: it returns the page HTML inline
 * and needs NO ASSETS / KV / D1 / R2 binding.
 *
 * Integrate in TWO lines at the very top of the worker's fetch handler, before
 * any SPA/catch-all routing:
 *
 *   import { handleNetworks } from "./canonical-route.js"; // or inline this file
 *   // ...
 *   async fetch(request, env, ctx) {
 *     const networks = handleNetworks(request);
 *     if (networks) return networks;
 *     // ...existing canonical routing continues unchanged...
 *   }
 *
 * Verify after deploy:
 *   curl -sI https://brmste.com/networks | head -n1     // expect HTTP/2 200
 */

const NETWORKS_HTML = `__EMBEDDED__`;

/**
 * Returns a Response for `/networks` (and `/networks/`), or null for every other
 * path so the caller falls through to its existing routing untouched.
 * @param {Request} request
 * @returns {Response|null}
 */
export function handleNetworks(request) {
  const { pathname } = new URL(request.url);
  if (pathname.replace(/\/+$/, "") !== "/networks") return null;
  return new Response(NETWORKS_HTML, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "public, max-age=60, stale-while-revalidate=300",
      "x-brmste-surface": "networks",
    },
  });
}

// Standalone fallback so this module is independently deployable too
// (`wrangler deploy` with main = canonical-route.js): serves /networks, 404 else.
export default {
  fetch(request) {
    return handleNetworks(request) || new Response("Not found", { status: 404 });
  },
};
"""


def render(html: str) -> str:
    embedded = escape_for_template_literal(html)
    return (
        JS_TEMPLATE.replace("__WORKER_ID__", CANONICAL_WORKER_ID)
        .replace("__WORKER__", CANONICAL_WORKER)
        .replace("__EMBEDDED__", embedded)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if canonical-route.js is out of sync with index.html",
    )
    args = parser.parse_args()

    if not SRC_HTML.is_file():
        print(f"build-networks-route: missing source {SRC_HTML}", file=sys.stderr)
        return 2

    html = SRC_HTML.read_text(encoding="utf-8")
    rendered = render(html)

    if args.check:
        current = OUT_JS.read_text(encoding="utf-8") if OUT_JS.is_file() else ""
        if current != rendered:
            print(
                "build-networks-route: canonical-route.js is STALE — "
                "run `python3 scripts/build-networks-route.py`",
                file=sys.stderr,
            )
            return 1
        print("build-networks-route: canonical-route.js in sync with index.html")
        return 0

    OUT_JS.write_text(rendered, encoding="utf-8")
    print(f"build-networks-route: wrote {OUT_JS.relative_to(REPO_ROOT)} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
