#!/usr/bin/env bash
# Verify domains/registry.json (and manifest.json if present) — no secrets required.
#
# Checks: valid JSON, schema tag, unique domains, roles in the allowed set, and
# that every domain declares all five cloud lanes (cloudflare, hetzner, aws,
# azure, siemens_iem). Safe to run locally, in CI, or by a cloud agent.
#
# BRMSTE LTD · Companies House 15310393 · GB2607860

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REGISTRY="${ROOT}/domains/registry.json"
MANIFEST="${ROOT}/domains/manifest.json"
LANES=(cloudflare hetzner aws azure siemens_iem)
ROLES='["primary","carbon_justice","coming_soon","redirect"]'

FAIL=0
ok()   { echo "OK   $*"; }
bad()  { echo "FAIL $*" >&2; FAIL=1; }

command -v jq >/dev/null 2>&1 || { echo "jq is required" >&2; exit 2; }

[[ -f "$REGISTRY" ]] || { bad "domains/registry.json missing"; exit 1; }
jq empty "$REGISTRY" 2>/dev/null && ok "registry.json is valid JSON" || { bad "registry.json invalid JSON"; exit 1; }

# Schema tag
[[ "$(jq -r '._meta.schema' "$REGISTRY")" == "brmste-domains-registry/v1" ]] \
  && ok "schema tag brmste-domains-registry/v1" || bad "unexpected _meta.schema"

# expected_total present and numeric
if jq -e '._meta.expected_total | type == "number"' "$REGISTRY" >/dev/null; then
  ok "expected_total = $(jq -r '._meta.expected_total' "$REGISTRY")"
else
  bad "_meta.expected_total missing or not a number"
fi

# _meta.clouds declares all five lanes
for lane in "${LANES[@]}"; do
  jq -e "._meta.clouds | has(\"$lane\")" "$REGISTRY" >/dev/null \
    && ok "_meta.clouds has lane: $lane" || bad "_meta.clouds missing lane: $lane"
done

verify_domain_array() {
  local file="$1" label="$2"
  local n dupes
  n=$(jq '.domains | length' "$file")
  ok "${label}: ${n} domain(s)"

  dupes=$(jq -r '[.domains[].domain] | group_by(.) | map(select(length>1) | .[0]) | .[]' "$file")
  if [[ -n "$dupes" ]]; then bad "${label}: duplicate domains: ${dupes//$'\n'/, }"; else ok "${label}: all domains unique"; fi

  # Roles in the allowed set
  local badroles
  badroles=$(jq -r --argjson roles "$ROLES" '[.domains[] | select(.role as $r | ($roles | index($r) | not)) | .domain] | .[]' "$file")
  if [[ -n "$badroles" ]]; then bad "${label}: invalid role on: ${badroles//$'\n'/, }"; else ok "${label}: all roles valid"; fi

  # Every domain declares all five cloud lanes
  local anyMissing=0
  for lane in "${LANES[@]}"; do
    local m
    m=$(jq -r --arg l "$lane" '[.domains[] | select((.clouds // {}) | has($l) | not) | .domain] | .[]' "$file")
    if [[ -n "$m" ]]; then bad "${label}: missing lane '$lane' on: ${m//$'\n'/, }"; anyMissing=1; fi
  done
  [[ "$anyMissing" -eq 0 ]] && ok "${label}: every domain declares all five cloud lanes"
}

verify_domain_array "$REGISTRY" "registry.json"

if [[ -f "$MANIFEST" ]]; then
  jq empty "$MANIFEST" 2>/dev/null && ok "manifest.json is valid JSON" || bad "manifest.json invalid JSON"
  verify_domain_array "$MANIFEST" "manifest.json"
else
  echo "SKIP manifest.json not present (generated by scripts/sync-cf-zones-to-manifest.sh)"
fi

if [[ "$FAIL" -ne 0 ]]; then
  echo "domains registry verification FAILED" >&2
  exit 1
fi
echo "domains registry verification PASSED"
